version: "3"

services:

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3312:3306"
    networks:
      - shopping-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shoppingcart
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 50s
      retries: 5

  docker-application:
    image: siminastefan/microservices
    container_name: shopping-container
    ports:
      - "8082:8080"
    networks:
      - shopping-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  db:
    image: mysql:latest
    container_name: mysql-user-container
    ports:
      - "3311:3306"
    networks:
      - shopping-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=usermicroservicedb
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 60s
      retries: 6

  user-application:
    image: user-image
    container_name: user-container
    ports:
      - "8080:8080"
    networks:
      - shopping-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

  mysqls:
    image: mysql:latest
    container_name: mysql-product-container
    ports:
      - "3310:3306"
    networks:
      - shopping-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 60s
      retries: 6

  product-application:
    image: product-image
    container_name: product-container
    ports:
      - "8081:8080"
    networks:
      - shopping-network
    depends_on:
      mysqls:
        condition: service_healthy
    restart: always

networks:
  shopping-network: