apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql-service
    app: shopping-cart
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-pod
    app: shopping-cart