apiVersion: v1
kind: Pod
metadata:
  name: shopping-pod
  labels:
    name: shopping-pod
    app: shopping-cart
spec:
  containers:
    - name: shopping
      image: siminastefan/microservices
      env:
        - name: MYSQL_DB_HOST
          value: "mysql"
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-password